/**
 * Netlify build step — no dependencies, no framework.
 *
 * All this does is write js/supabase-config.js using the SUPABASE_URL and
 * SUPABASE_ANON_KEY environment variables you set in the Netlify dashboard,
 * so those values never have to be typed into a tracked file by hand.
 *
 * If the environment variables aren't set (e.g. you haven't configured
 * Supabase yet, or you're just testing the site locally), this writes
 * empty values instead of failing the build — the site then simply runs
 * on the built-in js/config.js menu, exactly as it did before Supabase
 * existed.
 */
const fs = require("fs");
const path = require("path");

const url = process.env.SUPABASE_URL || "";
const key = process.env.SUPABASE_ANON_KEY || "";

if (!url || !key) {
  console.warn(
    "[build.js] SUPABASE_URL / SUPABASE_ANON_KEY are not set — deploying with the built-in menu only (no admin panel data). This is fine if that's intentional."
  );
}

const output = `/* AUTO-GENERATED by build.js at deploy time from Netlify environment
   variables. Do not edit this file directly — it gets overwritten on every
   deploy. To change these values, update them in the Netlify dashboard
   under Site settings -> Environment variables, then redeploy. */
window.SUPABASE_URL = ${JSON.stringify(url)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(key)};
`;

const outPath = path.join(__dirname, "js", "supabase-config.js");
fs.writeFileSync(outPath, output, "utf8");
console.log(`[build.js] Wrote ${outPath} (${url ? "Supabase configured" : "Supabase NOT configured"})`);
